### ISSUE TITLE
A VOIP demo addressing SipSocery issues

### ISSUE THREAD

**Issue by GeorgeS2019** [SakulFlee/Godot-WebRTC-Match-Maker#174]
I understand we have a video call demo

I wonder if we could also have **an audio VOIP** demo.

So it could address that it is possible through your project with Godot4 to address any possible issues why the [WPF VOIP ](https://github.com/sipsorcery-org/sipsorcery/issues/1062)app is challenging to implement. 

## Integration Tests
Referencing [recent replies regarding WebRTC integration tests](https://github.com/SakulFlee/Godot-WebRTC-Match-Maker/discussions/169#discussioncomment-8971513) in discussions

**Comment by GeorgeS2019** [comment]
Here is the bug

```cs
characteristics = selectedCaptureDevice.Characteristics[index];

//NOT
characteristics = selectedCaptureDevice.Characteristics[0];
```
https://github.com/SakulFlee/Godot-WebRTC-Match-Maker/blob/e2d7a94bad18efc6bab9ba94ca5f97b61e378be8/Godot%20Project/Demos/VideoCall/VideoCall.cs#L122

**Comment by GeorgeS2019** [comment]
Here are the logs :-)

```
Godot Engine v4.2.1.stable.mono.official.b09f793f5 - https://godotengine.org
 
[VideoCall] Found capture device: [DeviceONE] (DirectShow), Characteristics=36
[VideoCall] Characteristics:
[VideoCall] Found capture device: 1280x720 [RGB24, 30,000fps]
[VideoCall] Found capture device: 1280x720 [YUYV, 30,000fps]
[VideoCall] Found capture device: 960x540 [RGB24, 30,000fps]
[VideoCall] Found capture device: 960x540 [YUYV, 30,000fps]
[VideoCall] Found capture device: 848x480 [RGB24, 30,000fps]
[VideoCall] Found capture device: 848x480 [YUYV, 30,000fps]
[VideoCall] Found capture device: 640x480 [RGB24, 30,000fps]
[VideoCall] Found capture device: 640x480 [YUYV, 30,000fps]
[VideoCall] Found capture device: 640x360 [RGB24, 30,000fps]
[VideoCall] Found capture device: 640x360 [YUYV, 30,000fps]
[VideoCall] Found capture device: 424x240 [RGB24, 30,000fps]
[VideoCall] Found capture device: 424x240 [YUYV, 30,000fps]
[VideoCall] Found capture device: 352x288 [RGB24, 30,000fps]
[VideoCall] Found capture device: 352x288 [YUYV, 30,000fps]
[VideoCall] Found capture device: 320x240 [RGB24, 30,000fps]
[VideoCall] Found capture device: 320x240 [YUYV, 30,000fps]
[VideoCall] Found capture device: 320x180 [RGB24, 30,000fps]
[VideoCall] Found capture device: 320x180 [YUYV, 30,000fps]
[VideoCall] Found capture device: 1280x720 [RGB24, 1,000fps]
[VideoCall] Found capture device: 1280x720 [YUYV, 1,000fps]
[VideoCall] Found capture device: 960x540 [RGB24, 1,000fps]
[VideoCall] Found capture device: 960x540 [YUYV, 1,000fps]
[VideoCall] Found capture device: 848x480 [RGB24, 1,000fps]
[VideoCall] Found capture device: 848x480 [YUYV, 1,000fps]
[VideoCall] Found capture device: 640x480 [RGB24, 1,000fps]
[VideoCall] Found capture device: 640x480 [YUYV, 1,000fps]
[VideoCall] Found capture device: 640x360 [RGB24, 1,000fps]
[VideoCall] Found capture device: 640x360 [YUYV, 1,000fps]
[VideoCall] Found capture device: 424x240 [RGB24, 1,000fps]
[VideoCall] Found capture device: 424x240 [YUYV, 1,000fps]
[VideoCall] Found capture device: 352x288 [RGB24, 1,000fps]
[VideoCall] Found capture device: 352x288 [YUYV, 1,000fps]
[VideoCall] Found capture device: 320x240 [RGB24, 1,000fps]
[VideoCall] Found capture device: 320x240 [YUYV, 1,000fps]
[VideoCall] Found capture device: 320x180 [RGB24, 1,000fps]
[VideoCall] Found capture device: 320x180 [YUYV, 1,000fps]


[VideoCall] Found capture device: [DeviceTWO] (DirectShow), Characteristics=43
[VideoCall] Characteristics:
[VideoCall] Found capture device: 1280x720 [JPEG, 60,000fps]
[VideoCall] Found capture device: 640x480 [JPEG, 60,000fps]
[VideoCall] Found capture device: 4096x2160 [JPEG, 30,000fps]
[VideoCall] Found capture device: 3840x2160 [JPEG, 30,000fps]
[VideoCall] Found capture device: 2560x1440 [JPEG, 30,000fps]
[VideoCall] Found capture device: 1920x1080 [YUYV, 30,000fps]
[VideoCall] Found capture device: 1920x1080 [Unknown, 30,000fps] <==
[VideoCall] Found capture device: 1920x1080 [JPEG, 30,000fps]
[VideoCall] Found capture device: 1600x896 [YUYV, 30,000fps]
[VideoCall] Found capture device: 1600x896 [JPEG, 30,000fps]
[VideoCall] Found capture device: 1280x720 [YUYV, 30,000fps]
[VideoCall] Found capture device: 1280x720 [Unknown, 30,000fps] <==
[VideoCall] Found capture device: 1024x576 [YUYV, 30,000fps]
[VideoCall] Found capture device: 1024x576 [JPEG, 30,000fps]
[VideoCall] Found capture device: 960x540 [YUYV, 30,000fps]
[VideoCall] Found capture device: 960x540 [JPEG, 30,000fps]
[VideoCall] Found capture device: 800x600 [YUYV, 30,000fps]
[VideoCall] Found capture device: 800x600 [JPEG, 30,000fps]
[VideoCall] Found capture device: 848x480 [YUYV, 30,000fps]
[VideoCall] Found capture device: 848x480 [JPEG, 30,000fps]
[VideoCall] Found capture device: 800x448 [YUYV, 30,000fps]
[VideoCall] Found capture device: 800x448 [JPEG, 30,000fps]
[VideoCall] Found capture device: 640x480 [YUYV, 30,000fps]
[VideoCall] Found capture device: 640x480 [Unknown, 30,000fps] <==
[VideoCall] Found capture device: 640x360 [YUYV, 30,000fps]
[VideoCall] Found capture device: 640x360 [Unknown, 30,000fps] <==
[VideoCall] Found capture device: 640x360 [JPEG, 30,000fps]
[VideoCall] Found capture device: 440x440 [YUYV, 30,000fps]
[VideoCall] Found capture device: 480x270 [YUYV, 30,000fps]
[VideoCall] Found capture device: 480x270 [JPEG, 30,000fps]
[VideoCall] Found capture device: 340x340 [YUYV, 30,000fps]
[VideoCall] Found capture device: 424x240 [YUYV, 30,000fps]
[VideoCall] Found capture device: 424x240 [JPEG, 30,000fps]
[VideoCall] Found capture device: 352x288 [YUYV, 30,000fps]
[VideoCall] Found capture device: 352x288 [JPEG, 30,000fps]
[VideoCall] Found capture device: 320x240 [YUYV, 30,000fps]
[VideoCall] Found capture device: 320x240 [JPEG, 30,000fps]
[VideoCall] Found capture device: 320x180 [YUYV, 30,000fps]
[VideoCall] Found capture device: 320x180 [JPEG, 30,000fps]
[VideoCall] Found capture device: 176x144 [YUYV, 30,000fps]
[VideoCall] Found capture device: 176x144 [JPEG, 30,000fps]
[VideoCall] Found capture device: 160x120 [YUYV, 30,000fps]
[VideoCall] Found capture device: 160x120 [JPEG, 30,000fps]

[MatchMaker] Own UUID: 4a5a45ac-86bf-41e8-bd7d-6dfbd15d41f5
[MatchMaker] Host UUID: 4a5a45ac-86bf-41e8-bd7d-6dfbd15d41f5
[MatchMaker] Is Host: False
[WebRTC] ICE Server: stun.l.google.com:19302 (NO credentials)
[WebRTC] ICE Server: stun1.l.google.com:19302 (NO credentials)
[WebRTC] ICE Server: stun2.l.google.com:19302 (NO credentials)
[WebRTC] ICE Server: stun3.l.google.com:19302 (NO credentials)
[WebRTC] ICE Server: stun4.l.google.com:19302 (NO credentials)
[WebRTC] Peer created!
[WebRTC] Channel #0/'Main' got created!
[WebRTC] Channel #1/'Video' got created!
[WebRTC] Channel #2/'Audio' got created!
[WebRTC] Gathering State Changed: gathering
[WebRTC] ICE Connection State Changed: checking
[WebRTC] Signaling State Changed: have_remote_offer
[WebRTC] ICE Candidate: {"candidate":"candidate:1553396109 1 udp 2113937663 [ip] 63868 typ host generation 0","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":"HJYC"}
[WebRTC] Signaling State Changed: stable
[WebRTC] ICE Connection State Changed: connected
[WebRTC] Connection State Changed: connecting
[WebRTC] Connection State Changed: connected
[WebRTC] Channel #0/Main opened!
[WebRTC] Channel #1/Video opened!
[WebRTC] Channel #2/Audio opened!
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 216b (decompressed: 176128b)
[VideoCall@Audio] Received 216b (decompressed: 176128b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 232b (decompressed: 192512b)
[VideoCall@Audio] Received 232b (decompressed: 192512b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 228b (decompressed: 188416b)
[VideoCall@Audio] Received 228b (decompressed: 188416b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 228b (decompressed: 188416b)
[VideoCall@Audio] Received 228b (decompressed: 188416b)
[VideoCall@Audio] Received 234b (decompressed: 194560b)
[VideoCall@Audio] Received 234b (decompressed: 194560b)
[VideoCall@Audio] Received 228b (decompressed: 188416b)
[VideoCall@Audio] Received 228b (decompressed: 188416b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 228b (decompressed: 188416b)
[VideoCall@Audio] Received 228b (decompressed: 188416b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall] Device selected: [DeviceTWO] (DirectShow), Characteristics=43
[VideoCall] Characteristics chosen: 640x480 [JPEG, 60,000fps]
[VideoCall@Audio] Received 228b (decompressed: 188416b)
[VideoCall@Audio] Received 228b (decompressed: 188416b)
[VideoCall] Capture device opened and started!
  [VideoCall] Failed converting webcam data into something useable ...
System.NullReferenceException: Object reference not set to an instance of an object.
   at VideoCall.sendFrame(Image image, Int64 frameIndex) in [@]VideoCall\VideoCall.cs:line 229
   at VideoCall.OnNewFrame(PixelBufferScope pixelBuffer) in [@]VideoCall\VideoCall.cs:line 154
   at FlashCap.FrameProcessors.DelegatedQueuingProcessor.ThreadEntry() in /_/FlashCap.Core/FrameProcessors/QueuingProcessor.cs:line 159
  [VideoCall] Failed converting webcam data into something useable ...
System.NullReferenceException: Object reference not set to an instance of an object.
   at VideoCall.sendFrame(Image image, Int64 frameIndex) in [@]VideoCall\VideoCall.cs:line 229
   at VideoCall.OnNewFrame(PixelBufferScope pixelBuffer) in [@]VideoCall\VideoCall.cs:line 154
   at FlashCap.FrameProcessors.DelegatedQueuingProcessor.ThreadEntry() in /_/FlashCap.Core/FrameProcessors/QueuingProcessor.cs:line 159
[VideoCall@Audio] Received 230b (decompressed: 190464b)
[VideoCall@Audio] Received 230b (decompressed: 190464b)
  [VideoCall] Failed converting webcam data into something useable ...
System.NullReferenceException: Object reference not set to an instance of an object.
   at VideoCall.sendFrame(Image image, Int64 frameIndex) in [@]VideoCall\VideoCall.cs:line 229
   at VideoCall.OnNewFrame(PixelBufferScope pixelBuffer) in [@]VideoCall\VideoCall.cs:line 154
   at FlashCap.FrameProcessors.DelegatedQueuingProcessor.ThreadEntry() in /_/FlashCap.Core/FrameProcessors/QueuingProcessor.cs:line 159
  [VideoCall] Failed converting webcam data into something useable ...
System.NullReferenceException: Object reference not set to an instance of an object.
   at VideoCall.sendFrame(Image image, Int64 frameIndex) in [@]VideoCall\VideoCall.cs:line 229
   at VideoCall.OnNewFrame(PixelBufferScope pixelBuffer) in [@]VideoCall\VideoCall.cs:line 154
   at FlashCap.FrameProcessors.DelegatedQueuingProcessor.ThreadEntry() in /_/FlashCap.Core/FrameProcessors/QueuingProcessor.cs:line 159
  [VideoCall] Failed converting webcam data into something useable ...
System.NullReferenceException: Object reference not set to an instance of an object.
   at VideoCall.sendFrame(Image image, Int64 frameIndex) in [@]VideoCall\VideoCall.cs:line 229
   at VideoCall.OnNewFrame(PixelBufferScope pixelBuffer) in [@]VideoCall\VideoCall.cs:line 154
   at FlashCap.FrameProcessors.DelegatedQueuingProcessor.ThreadEntry() in /_/FlashCap.Core/FrameProcessors/QueuingProcessor.cs:line 159
  [VideoCall] Failed converting webcam data into something useable ...
System.NullReferenceException: Object reference not set to an instance of an object.
   at VideoCall.sendFrame(Image image, Int64 frameIndex) in [@]VideoCall\VideoCall.cs:line 229
   at VideoCall.OnNewFrame(PixelBufferScope pixelBuffer) in [@]VideoCall\VideoCall.cs:line 154
   at FlashCap.FrameProcessors.DelegatedQueuingProcessor.ThreadEntry() in /_/FlashCap.Core/FrameProcessors/QueuingProcessor.cs:line 159
  [VideoCall] Failed converting webcam data into something useable ...

```

**Comment by GeorgeS2019** [comment]
The text came from addon is covered when building. Is this normal?

![Godot_v4 2 1-stable_mono_win64_M7tnpOZ6kU](https://github.com/SakulFlee/Godot-WebRTC-Match-Maker/assets/49812372/ec7ec05a-6ae7-4b63-869f-041c3d91fe5a)

**Comment by GeorgeS2019** [comment]
what is the purpose of the content?

![image](https://github.com/SakulFlee/Godot-WebRTC-Match-Maker/assets/49812372/252f797e-7725-49bd-b5e3-5a208830f5bc)

**Comment by SakulFlee** [comment]
> Here are the logs :-)
> 
> The Winform FlashCap works with the **DeviceTWO** camera by adding additional check for **unkonwn**
> 
> https://github.com/kekyo/FlashCap/blob/854186a445e494548480ae0d6b607c1bf009eb57/samples/FlashCap.WindowsForms/MainForm.cs#L48C1-L58C7
> ```cs
> #if false
>             // Request video characteristics strictly:
>             // Will raise exception when parameters are not accepted.
>             var characteristics = new VideoCharacteristics(
>                 PixelFormats.JPEG, 1920, 1080, 60);
> #else
>             // Or, you could choice from device descriptor:
>             // Hint: Show up video characteristics into ComboBox and like.
>             var characteristics = descriptor0.Characteristics.
>                 FirstOrDefault(c => c.PixelFormat != PixelFormats.Unknown);
> #endif
> ```
> 
> 

Strange. Can't see your logs on GitHub but in the email I received. What you said there is actually on purpose and documented in the description:

Godot itself only supports certain formats.
Index 0 is, supposedly at least, a adapter format that always will work. (Or should that is ...)

I didn't want to overcomplicate the demo by making a drop down or something like it where you can select the output device.
This is for the end user (i.e. you) to implement and doesn't help the demo showcasing how this project works. Instead, it would just overcomplicate things.

We could change it to the above which may or may not throw an exception, but at that point it's the same as now: will only work on _some_ devices. The chances of the current solution not working should be actually higher than trying to force a format.
(Since index 0 **must** exist on a capture device.)

**Comment by SakulFlee** [comment]
> The text came from addon is covered when building. Is this normal?
> ![image](https://github.com/SakulFlee/Godot-WebRTC-Match-Maker/assets/49812372/cc66ed9f-fc9f-4233-9204-04b7f68a2999)
> 
> ![Godot_v4 2 1-stable_mono_win64_M7tnpOZ6kU](https://github.com/SakulFlee/Godot-WebRTC-Match-Maker/assets/49812372/ec7ec05a-6ae7-4b63-869f-041c3d91fe5a)
> 

Unfortunately. Try reloading Godot after compiling.

**Comment by SakulFlee** [comment]
> what is the purpose of the content?
> This is preventing opening the VS2022 project unless I delete it
> 
> ![image](https://github.com/SakulFlee/Godot-WebRTC-Match-Maker/assets/49812372/252f797e-7725-49bd-b5e3-5a208830f5bc)
> 

It's a standard CSProj file.
There shouldn't be anything in there preventing it from opening. It does open fine for me. Can you give me some better error description?

But as you can see, it's defining dependencies for the project and makes them so that the building process copies them into the build folder for Godot to work.

You may have forgotten to initialize the project. See here: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-restore

**Comment by GeorgeS2019** [comment]
> But as you can see, it's defining dependencies for the project and makes them so that the building process copies them into the build folder for Godot to work.
![image](https://github.com/SakulFlee/Godot-WebRTC-Match-Maker/assets/49812372/471ab3c5-cb8f-4c09-9f14-e5eda4c68567)

I deleted this part and it works ALWAYS for all godot 4 csharp project

**Comment by GeorgeS2019** [comment]
> When doing my research it was apparent that the device characteristics at index 0 first of all must exist (since first index) and secondly must be in a default format. Godot is very selective about which formats it allows and I didn't want to add any complicated conversion logic between formats.

I went through the WinForm and WPF demo examples for FlashCap

There are good tips to learn from as some camera return UNKNOWN format

**Comment by SakulFlee** [comment]
> > When doing my research it was apparent that the device characteristics at index 0 first of all must exist (since first index) and secondly must be in a default format. Godot is very selective about which formats it allows and I didn't want to add any complicated conversion logic between formats.
> 
> I went through the WinForm and WPF demo examples for FlashCap
> 
> There are good tips to learn from as some camera return UNKNOWN format

Yes, but like I said: Godot is very iffy on which formats it's supporting and I don't want to overcomplicate the examples. i.e. only formats that Godot supports will be supported.

**Comment by GeorgeS2019** [comment]
> Yes, but like I said: Godot is very iffy on which formats it's supporting and I don't want to overcomplicate the examples. i.e. only formats that Godot supports will be supported.

I got the camera working now. 

There is nothing wrong with the FlashCap, just need to make both FlashCap and Godot4 tango as ONE

**Comment by SakulFlee** [comment]
> > And it does work just fine.
> > Any issue logs?
> 
> VS2022 simple refuses to open
> 

If I open it, it just opens fine without any issues.
Also builds fine (see CI).

Am unsure what the issue is you are having there.

**Comment by SakulFlee** [comment]
> I also start putting into gdUnit4 test adapter to start going through the codes to understand them.
> 
> Thank you for doing a Good Job.

Alrighty. Let me know once you make some progress with that!
Keep in mind the requirements I was making.

Might as well convert that to an issue too...
